# Generated by Django 6.0.3 on 2026-03-09 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orgs', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgRole',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable role name. e.g. 'Teacher', 'Student', 'admin'", max_length=100)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles are locked — cannot be renamed or deleted.')),
                ('description', models.TextField(blank=True, default='')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='Orgs.organization')),
            ],
            options={
                'verbose_name': 'Org Role',
                'verbose_name_plural': 'Org Roles',
                'db_table': 'org_roles',
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account is active. Deactivate instead of deleting.')),
                ('is_staff', models.BooleanField(default=False, help_text='Django admin access only. Not related to platform roles.')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='', help_text="Internal notes about this super user (e.g., 'Lead developer').")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Super User',
                'verbose_name_plural': 'Super Users',
                'db_table': 'super_users',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag_key', models.CharField(help_text="Snake_case key. e.g. 'beta_gradebook', 'new_attendance_ui'", max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='', help_text='Internal description of what this flag controls.')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='Users.orgrole')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'feature_flags',
                'unique_together': {('role', 'flag_key')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(help_text="Module/section identifier. e.g. 'attendance', 'gradebook'", max_length=100)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('export', 'Export')], max_length=50)),
                ('allowed', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Users.orgrole')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
                'indexes': [models.Index(fields=['role', 'module'], name='idx_role_module')],
                'unique_together': {('role', 'module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='SystemAdminSession',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=255)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sys_admin_sessions', to='Orgs.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sys_admin_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Admin Session',
                'verbose_name_plural': 'System Admin Sessions',
                'db_table': 'system_admin_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_sysadmin_session_user'), models.Index(fields=['org', 'is_active'], name='idx_sysadmin_session_org')],
            },
        ),
        migrations.CreateModel(
            name='RefreshTokenRecord',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jti', models.CharField(db_index=True, help_text='JWT ID — unique identifier from the token payload.', max_length=255, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refresh Token Record',
                'verbose_name_plural': 'Refresh Token Records',
                'db_table': 'refresh_token_records',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['user', 'is_revoked'], name='idx_refresh_token_user'), models.Index(fields=['expires_at'], name='idx_refresh_token_expiry')],
            },
        ),
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('is_system_admin', models.BooleanField(default=False, help_text="True only for the org's designated system admin. Only one per org (enforced by partial unique index).")),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='Orgs.organization')),
                ('role', models.ForeignKey(help_text="The user's role within this org. Must belong to the same org.", on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='Users.orgrole')),
                ('approved_by', models.ForeignKey(blank=True, help_text='The user (admin or system_admin) who approved this membership.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='OneToOne enforces one-org-per-user. Change to ForeignKey when scaling.', on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Org Membership',
                'verbose_name_plural': 'Org Memberships',
                'db_table': 'org_memberships',
                'indexes': [models.Index(fields=['org', 'status'], name='idx_membership_org_status'), models.Index(fields=['org', 'role'], name='idx_membership_org_role')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_system_admin', True)), fields=('org',), name='uq_one_sysadmin_per_org')],
            },
        ),
    ]
