# Generated by Django 6.0.3 on 2026-03-18 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0002_sub_organization'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmembership',
            name='sub_org',
            field=models.ForeignKey(blank=True, help_text='Optional scoping to a sub-organization (e.g. a department or campus). NULL = member of the parent org with no sub-org restriction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='Orgs.suborganization'),
        ),
    ]
