# Generated by Django 6.0.3 on 2026-03-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_sub_org_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Contact phone number.', max_length=20),
        ),
        migrations.AlterField(
            model_name='orgmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('waiting_approval', 'Waiting for Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
