# Generated by Django 6.0.3 on 2026-03-18 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_phone_number_alter_orgmembership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgrole',
            name='role_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin'), ('owner', 'Owner'), ('parent', 'Parent'), ('vendor', 'Vendor')], default='staff', help_text='Core classification driving permissions and profile fields.', max_length=20),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=3)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('religion', models.CharField(blank=True, default='', max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='persons/photos/')),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state_or_province', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('birth_certificate', 'Birth Certificate'), ('driving_license', 'Driving License'), ('other', 'Other')], default='other', max_length=50)),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('issued_by', models.CharField(blank=True, default='', max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('front_image', models.FileField(upload_to='persons/documents/')),
                ('back_image', models.FileField(blank=True, upload_to='persons/documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='Users.person')),
            ],
            options={
                'verbose_name': 'Identity Document',
                'verbose_name_plural': 'Identity Documents',
                'db_table': 'identity_documents',
                'indexes': [models.Index(fields=['person'], name='idx_identity_doc_person')],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('sibling', 'Sibling'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandparent', 'Grandparent'), ('legal_guardian', 'Legal Guardian'), ('other', 'Other')], default='other', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, default='')),
                ('occupation', models.CharField(blank=True, default='', max_length=150)),
                ('parent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profiles', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='Users.person')),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'db_table': 'guardians',
                'indexes': [models.Index(fields=['person'], name='idx_guardian_person')],
            },
        ),
    ]
