# Generated by Django 6.0.3 on 2026-03-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_orgrole_role_type_person_identitydocument_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
