# Generated by Django 6.0.3 on 2026-03-09 05:39

import Orgs.models.legal
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text="Immutable URL-safe identifier. Set at creation, never changed. e.g. 'greenwood-high'. Used internally to reference the org.", max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Master switch for the org. When False: all logins blocked, API access denied, public page returns 503.')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Set when is_active is toggled to False. Auditing purposes.', null=True)),
                ('deactivation_reason', models.TextField(blank=True, default='', help_text='Reason recorded by super_user when deactivating.')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationLegal',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_full_name', models.CharField(blank=True, default='', help_text='Full legal name of the school owner or principal.', max_length=255)),
                ('owner_title', models.CharField(blank=True, default='', help_text="Title/designation. e.g. 'Principal', 'Chairman', 'Director'", max_length=100)),
                ('owner_id_type', models.CharField(blank=True, default='', help_text="Type of ID provided. e.g. 'National ID', 'Passport'", max_length=50)),
                ('owner_id_number', models.CharField(blank=True, default='', help_text="Owner's national ID or passport number. SENSITIVE — encrypt at rest in production.", max_length=100)),
                ('registration_number', models.CharField(blank=True, default='', help_text='Official school registration number issued by the government body.', max_length=100)),
                ('registration_date', models.DateField(blank=True, help_text='Date the school was officially registered.', null=True)),
                ('registered_with', models.CharField(blank=True, default='', help_text="Name of the government body the school is registered with. e.g. 'Ministry of Education, Nepal'", max_length=255)),
                ('registration_document', models.FileField(blank=True, help_text='Scanned copy of the official registration certificate. Private — not public.', null=True, upload_to=Orgs.models.legal.legal_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('registration_expiry', models.DateField(blank=True, help_text='Registration expiry date if applicable.', null=True)),
                ('tax_id_number', models.CharField(blank=True, default='', help_text='Tax identification number / PAN / VAT number.', max_length=100)),
                ('vat_registered', models.BooleanField(default=False, help_text='Whether the school is VAT registered.')),
                ('vat_number', models.CharField(blank=True, default='', help_text='VAT registration number (if VAT registered).', max_length=100)),
                ('accreditation_status', models.CharField(choices=[('accredited', 'Accredited'), ('pending', 'Pending'), ('expired', 'Expired'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20)),
                ('accreditation_body', models.CharField(blank=True, default='', help_text="Name of the accrediting organization. e.g. 'Nepal Accreditation Council'", max_length=255)),
                ('accreditation_number', models.CharField(blank=True, default='', help_text='Certificate or license number issued by the accrediting body.', max_length=100)),
                ('accreditation_valid_from', models.DateField(blank=True, null=True)),
                ('accreditation_valid_until', models.DateField(blank=True, help_text='Expiry date of the accreditation. Alerts should fire before this.', null=True)),
                ('accreditation_document', models.FileField(blank=True, help_text='Scanned accreditation certificate. Private — not public.', null=True, upload_to=Orgs.models.legal.accreditation_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Private notes visible only to super_user via terminal/admin. e.g. billing issues, compliance flags, support history.')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal', to='Orgs.organization')),
            ],
            options={
                'verbose_name': 'Organization Legal',
                'verbose_name_plural': 'Organization Legal Records',
                'db_table': 'org_legal',
            },
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Full official name of the school. e.g. 'Greenwood High School'", max_length=255)),
                ('short_name', models.CharField(blank=True, default='', help_text="Abbreviated name for display in tight spaces. e.g. 'GHS'", max_length=50)),
                ('school_type', models.CharField(blank=True, choices=[('pre_primary', 'Pre-Primary'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('higher_sec', 'Higher Secondary'), ('university', 'University'), ('vocational', 'Vocational / Technical'), ('other', 'Other')], default='', help_text='The level/type of the institution.', max_length=20)),
                ('tagline', models.CharField(blank=True, default='', help_text="Motto or tagline shown on the public page. e.g. 'Excellence in Education'", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Short about/description paragraph for the public landing page.')),
                ('established_year', models.PositiveSmallIntegerField(blank=True, help_text='Year the school was founded. e.g. 1995', null=True)),
                ('logo', models.ImageField(blank=True, help_text='School logo. Displayed on public page and dashboards.', null=True, upload_to='org_logos/%Y/')),
                ('favicon', models.ImageField(blank=True, help_text="Browser tab icon for the org's hosted frontend.", null=True, upload_to='org_favicons/%Y/')),
                ('cover_image', models.ImageField(blank=True, help_text='Hero/banner image shown on the public landing page.', null=True, upload_to='org_covers/%Y/')),
                ('primary_color', models.CharField(blank=True, default='', help_text="Hex color code for org branding. e.g. '#1A3C6E'", max_length=7)),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state_province', models.CharField(blank=True, default='', help_text='State, province, or district.', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', help_text='Country name or ISO 3166-1 alpha-2 code.', max_length=100)),
                ('phone_primary', models.CharField(blank=True, default='', help_text='Main contact phone number.', max_length=30)),
                ('phone_secondary', models.CharField(blank=True, default='', help_text='Secondary / alternate phone number.', max_length=30)),
                ('email_primary', models.EmailField(blank=True, default='', help_text='Main public contact email. e.g. info@greenwood.edu', max_length=254)),
                ('email_admissions', models.EmailField(blank=True, default='', help_text='Admissions-specific email (optional).', max_length=254)),
                ('website', models.URLField(blank=True, default='', help_text="School's external website (if different from the platform domain).", validators=[django.core.validators.URLValidator()])),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Orgs.organization')),
            ],
            options={
                'verbose_name': 'Organization Profile',
                'verbose_name_plural': 'Organization Profiles',
                'db_table': 'org_profiles',
            },
        ),
        migrations.CreateModel(
            name='OrgDomain',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(db_index=True, help_text="Full domain name without protocol or trailing slash. e.g. 'greenwood.edu' or 'app.greenwood.edu'", max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Only one domain per org can be primary. Enforced by DB partial unique index.')),
                ('is_verified', models.BooleanField(default=False, help_text='Super user marks as verified after DNS confirmation. Unverified domains are NOT used for auth routing.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text="Internal notes. e.g. 'Old domain — alias until March 2026'")),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='Orgs.organization')),
            ],
            options={
                'verbose_name': 'Org Domain',
                'verbose_name_plural': 'Org Domains',
                'db_table': 'org_domains',
                'indexes': [models.Index(fields=['domain', 'is_verified'], name='idx_domain_verified')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('org',), name='uq_one_primary_domain_per_org')],
            },
        ),
    ]
