# Generated by Django 6.0.3 on 2026-03-18 03:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrganization',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable name. e.g. 'Science Department', 'Birtamod Campus'", max_length=200)),
                ('code', models.SlugField(help_text="URL-safe identifier, unique within the parent org. e.g. 'sci-dept', 'birtamod-campus'. Set at creation.", max_length=100)),
                ('sub_type', models.CharField(choices=[('department', 'Department'), ('campus', 'Campus'), ('branch', 'Branch'), ('faculty', 'Faculty'), ('other', 'Other')], default='department', help_text='Category of this sub-organization.', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this sub-organization.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive sub-orgs are hidden but not removed.')),
                ('parent_org', models.ForeignKey(help_text='The parent tenant organisation this sub-org belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_orgs', to='Orgs.organization')),
            ],
            options={
                'verbose_name': 'Sub-Organization',
                'verbose_name_plural': 'Sub-Organizations',
                'db_table': 'sub_organizations',
                'ordering': ['parent_org', 'name'],
                'unique_together': {('parent_org', 'code')},
            },
        ),
    ]
