# Generated by Django 6.0.3 on 2026-03-20 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0002_sub_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('auth', 'Auth'), ('membership', 'Membership'), ('org_changes', 'Org Changes'), ('system', 'System')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=50)),
                ('action', models.CharField(max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='Orgs.organization')),
            ],
            options={
                'db_table': 'org_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org', '-created_at'], name='org_activit_org_id_c0de78_idx'), models.Index(fields=['org', 'category'], name='org_activit_org_id_7431c6_idx'), models.Index(fields=['org', 'severity'], name='org_activit_org_id_e0a947_idx'), models.Index(fields=['actor'], name='org_activit_actor_i_5916bc_idx')],
            },
        ),
    ]
