# Generated by Django 6.0.3 on 2026-03-22 08:48

import Orgs.models.owner
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0003_orgactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationlegal',
            name='owner_full_name',
        ),
        migrations.RemoveField(
            model_name='organizationlegal',
            name='owner_id_number',
        ),
        migrations.RemoveField(
            model_name='organizationlegal',
            name='owner_id_type',
        ),
        migrations.RemoveField(
            model_name='organizationlegal',
            name='owner_title',
        ),
        migrations.CreateModel(
            name='OrgOwner',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_legal_name', models.CharField(help_text="Full legal name exactly as it appears on official documents. May differ from the platform user's display name.", max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Marks this as the primary legal owner. Only one primary owner allowed per org — enforced by DB constraint.')),
                ('pan_number', models.CharField(blank=True, default='', help_text='PAN card number. SENSITIVE — encrypt at rest in production.', max_length=100)),
                ('pan_document', models.FileField(blank=True, help_text='Scanned copy of PAN card. Private — never served publicly.', null=True, upload_to=Orgs.models.owner.owner_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('national_id_number', models.CharField(blank=True, default='', help_text='National ID card number. SENSITIVE.', max_length=100)),
                ('national_id_document', models.FileField(blank=True, help_text='Scanned national ID card. Private.', null=True, upload_to=Orgs.models.owner.owner_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('driving_license_number', models.CharField(blank=True, default='', help_text='Driving license number. Optional.', max_length=100)),
                ('driving_license_document', models.FileField(blank=True, help_text='Scanned driving license. Optional. Private.', null=True, upload_to=Orgs.models.owner.owner_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('passport_number', models.CharField(blank=True, default='', help_text='Passport number. Optional.', max_length=100)),
                ('passport_document', models.FileField(blank=True, help_text='Scanned passport. Optional. Private.', null=True, upload_to=Orgs.models.owner.owner_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('ownership_document', models.FileField(blank=True, help_text='Official proof of ownership — deed, board resolution, certificate of incorporation, or equivalent. Private.', null=True, upload_to=Orgs.models.owner.owner_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('org', models.ForeignKey(help_text='The organization this owner belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='Orgs.organization')),
                ('user', models.ForeignKey(blank=True, help_text='Optional link to a platform user account. Set if the owner also uses the platform. Null for external owners with no platform account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Org Owner',
                'verbose_name_plural': 'Org Owners',
                'db_table': 'org_owners',
                'ordering': ['-is_primary', 'full_legal_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('org',), name='uq_one_primary_owner_per_org')],
            },
        ),
    ]
