# Generated by Django 6.0.3 on 2026-03-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0004_remove_organizationlegal_owner_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='secondary_color',
            field=models.CharField(blank=True, default='', help_text="Secondary hex color code for org branding. e.g. '#F59E0B'", max_length=7),
        ),
        migrations.AlterField(
            model_name='organizationlegal',
            name='accreditation_status',
            field=models.CharField(choices=[('accredited', 'Accredited'), ('pending', 'Pending'), ('expired', 'Expired'), ('not_applicable', 'Not Applicable'), ('provisionally_accredited', 'Provisionally Accredited')], default='not_applicable', max_length=30),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text="Primary hex color code for org branding. e.g. '#1A3C6E'", max_length=7),
        ),
    ]
